### PR TITLE
fixes variable name errors and type errors

### PR DESCRIPTION
**Pull request by MarissaLZ**

### CODE REVIEW

**Comment by ericabasak** [comment]
How did you find using debugging tools?

**Comment by MarissaLZ** [comment]
There was a lot of refreshing. I think I could be better at
using/understanding the debugger. Some of the simpler errors I could spot
quickly without the debugger (misspelling or misuse of the == operator).

**Comment by ericabasak** [comment]
That's good that a lot of it stood out to you easily :) How are you feeling overall about the class?

**Comment by MarissaLZ** [comment]
Sorry I forgot to reply back!
I feel good so far!. The only thing that took me a while to understand was
CSS. It was frustrating for a while, but I feel like I'm ok with it now.
Everything else hasn't been too bad. I've applied to take the front-end
(React) course next.

**Comment by ericabasak** [comment]
Happy to hear your feeling good about it. I think you will really like React, at least I really liked it!

**Pull request merged**
